

actions:
  vergence:
      - -1.125
      - -0.5625
      - -0.28125
      - -0.140625
      - 0.
      - 0.140625
      - 0.28125
      - 0.5625
      - 1.125
  cyclo:
      - -3.58
      - -1.79
      - 0.0
      - 1.79
      - 3.58
n_actions:
  vergence: 9
  cyclo: 5
